# Generated by Django 3.2.7 on 2021-11-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_image', models.CharField(max_length=255)),
                ('cat_description', models.TextField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=255)),
                ('cat_id', models.IntegerField()),
                ('pro_image', models.CharField(max_length=255)),
                ('pro_price', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
