# Generated by Django 3.2.7 on 2021-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booktour',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_name', models.CharField(max_length=255)),
                ('cus_add', models.CharField(max_length=255)),
                ('cus_mail', models.CharField(max_length=255)),
                ('cus_phone', models.CharField(max_length=11)),
                ('cus_soluong', models.IntegerField()),
                ('cus_date_start', models.CharField(max_length=255)),
                ('cus_date_end', models.CharField(max_length=255)),
                ('tour_name', models.CharField(max_length=255)),
                ('tour_price', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'book_tour',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_image', models.CharField(max_length=255)),
                ('cat_description', models.TextField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Customer_Comment',
            fields=[
                ('cmt_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=255)),
                ('cat_id', models.IntegerField()),
                ('pro_image', models.CharField(max_length=255)),
                ('pro_price', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
